/* @generated by tools/vite-plugins/script-ctx-codegen.ts — DO NOT EDIT.
 * Source of truth: src/renderer/lib/script-ctx.ts (ScriptCtx interface).
 * Regenerate: npm run dev / npm run build (the Vite plugin runs automatically).
 */
/* eslint-disable */
// prettier-ignore
export const SCRIPT_CTX_DTS = `
/** Um item do personagem (equipamento ou do inventário). */
declare interface Item {
  /** Posição do item no equipamento ou na bolsa (\`0..14\`). */
  readonly slot: number;
  /** Bolsa do item (\`0..3\`). Só em itens do inventário. */
  readonly bag?: number;
  /** ID do item. */
  readonly itemId: number;
  /** Nome do item, já com sufixos como \`+N\` e \`[G]\`. */
  readonly name: string;
  /** Nível de refino (\`+1..+16\`). */
  readonly refineLevel?: number;
  /** Quantidade na pilha (\`1..500\`). */
  readonly stackCount?: number;
  /** Item preso (valores na tabela abaixo da página). */
  readonly immovable?: 1 | 2 | 3;
  /** Como o jogo reage ao usar o item (valores na tabela abaixo da página). */
  readonly useKind: "direto" | "pergaminho" | "popup" | "painel" | "equipamento" | "bloqueado";
  /**
   * Usa o item (consome), disparado depois que o script termina. Só existe em
   * consumíveis de uso direto (\`useKind === 'direto'\`).
   *
   * @example \`\`\`js
   * // Usa o melhor Pergaminho da Água(M) disponível, do LV8 ao LV1
   * const inv = ctx.player.inventory;
   * if (inv.has(784)) inv.find(784)?.use();
   * else if (inv.has(783)) inv.find(783)?.use();
   * // …
   * else if (inv.has(777)) inv.find(777)?.use();
   * \`\`\`
   */
  use?(): void;
  /**
   * Apaga o item da bolsa (joga fora). **O efeito só acontece depois que o
   * script termina**, não na hora da chamada — igual a \`use()\`. Enquanto o
   * script ainda roda, o item continua visível no inventário.
   *
   * Só existe em itens do inventário (bolsas), nunca em equipamentos.
   * Alguns itens não podem ser apagados pelo jogo; nesse caso o item volta
   * para a bolsa sozinho. Se o script chamar \`delete()\` mais de uma vez,
   * vale a **última** chamada (só um item é apagado por execução).
   *
   * @example \`\`\`js
   * // Apaga o primeiro Selo Élfico (id 2490) da bolsa
   * const lixo = ctx.player.inventory.find(2490);
   * if (lixo) lixo.delete();
   * \`\`\`
   */
  delete?(): void;
  /** Os atributos do item, como no tooltip. Cada um traz \`id\`, \`label\` e \`value\`. */
  readonly stats: ReadonlyArray<{
    /** Identificador do atributo (ex.: \`"damage"\`, \`"hp"\`). */
    readonly id: string;
    /** Nome do atributo em português, igual ao tooltip. */
    readonly label: string;
    /** Valor numérico do atributo. */
    readonly value: number;
  }>;
  /**
   * Só existe em pergaminhos (\`useKind === 'pergaminho'\`). Na caça,
   * \`destinations\` lista os lugares; em retorno/teleporte/portal, vem vazia.
   */
  readonly scroll?: {
    /** Lugares para onde o pergaminho pode levar. Nomes podem repetir — passe o objeto inteiro para \`use\`, nunca só o nome. */
    readonly destinations: ReadonlyArray<{
      /** Nome do local (pode repetir). */
      readonly name: string;
      /** Posição X do destino, em tiles. */
      readonly x: number;
      /** Posição Y do destino, em tiles. */
      readonly y: number;
    }>;
    /**
     * Usa o pergaminho. O teleporte dispara depois que o script termina e
     * leva cerca de 5 segundos. Na caça, passe um destino de
     * \`scroll.destinations\`; no retorno/portal, chame sem argumento.
     *
     * @param destino Destino vindo de \`scroll.destinations\` (só na caça). Omita no retorno/portal.
     * @example \`\`\`js
     * const pergaminho = ctx.player.inventory.find(3437);
     * if (pergaminho?.scroll) {
     *   const pos = pergaminho.scroll.destinations.find((pos) => pos.name == 'Local do Guerreiro Amon');
     *   pergaminho.scroll.use(pos);
     * } else {
     *   throw new Error('Está sem pergaminho de caça Nipple');
     * }
     * \`\`\`
     */
    use(destino?: {
      x: number;
      y: number;
    }): void;
  };
}
/** Uma peça visível de uma entidade: só id e nome. */
declare interface ItemShort {
  /** Número (id) do item. */
  readonly itemId: number;
  /** Nome do item. Pode vir vazio no modelo do corpo de um monstro. */
  readonly name: string;
}
/** Um NPC, monstro ou outro jogador no mapa. */
declare interface Entidade {
  /** Identificador da entidade. Vale só enquanto você está conectado: muda a cada novo login. */
  readonly index: number;
  /** Nome da entidade. */
  readonly name: string;
  /** Posição da entidade no mapa atual, em tiles (\`x\`, \`y\`). */
  readonly position: {
    readonly x: number;
    readonly y: number;
  };
  /**
   * O visual da entidade: o modelo do corpo e as peças que ela usa. Os slots
   * são os mesmos de \`ctx.player.equipment\`.
   */
  readonly appearance: {
    /** Modelo do corpo (que tipo de criatura ou NPC é). */
    readonly body: ItemShort | null;
    /** Capacete à vista. */
    readonly helmet: ItemShort | null;
    /** Peitoral à vista. */
    readonly armor: ItemShort | null;
    /** Calça à vista. */
    readonly pants: ItemShort | null;
    /** Luvas à vista. */
    readonly gloves: ItemShort | null;
    /** Botas à vista. */
    readonly boots: ItemShort | null;
    /** Arma à vista. */
    readonly weapon: ItemShort | null;
    /** Mão secundária à vista. */
    readonly offhand: ItemShort | null;
    /** Brinco à vista. */
    readonly earring: ItemShort | null;
    /** Especial 2 à vista. */
    readonly special2: ItemShort | null;
    /** Especial 1 à vista. */
    readonly special1: ItemShort | null;
    /** Especial 3 à vista. */
    readonly special3: ItemShort | null;
    /** Traje à vista. */
    readonly costume: ItemShort | null;
    /** Fada à vista. */
    readonly fairy: ItemShort | null;
    /** Montaria à vista. */
    readonly mount: ItemShort | null;
    /** Capa à vista. */
    readonly cape: ItemShort | null;
  };
  /**
   * Se a entidade está a até \`tiles\` passos do personagem.
   *
   * @param tiles Distância máxima, em tiles (passos).
   * @example \`\`\`js
   * const lan = ctx.npcs.find((n) => n.name === 'LAN A');
   * if (lan?.isWithin(5)) ctx.macro.goToMarker('ENTER_LAN');
   * \`\`\`
   */
  isWithin(tiles: number): boolean;
}
/**
 * O objeto \`ctx\` que seu macro usa para ler o jogo e tomar decisões.
 *
 * Leituras de \`player\`, \`npcs\`, \`monsters\` e \`otherPlayers\` são sempre
 * atualizadas: cada acesso traz o estado do jogo naquele instante.
 */
declare interface ScriptCtx {
  /** Estado do seu personagem. */
  readonly player: {
    /** HP atual. */
    readonly hp: number;
    /** HP máximo. */
    readonly maxHp: number;
    /** MP atual. */
    readonly mp: number;
    /** MP máximo. */
    readonly maxMp: number;
    /** Posição do personagem no mapa atual, em tiles (\`x\`, \`y\`). */
    readonly position: {
      readonly x: number;
      readonly y: number;
    };
    /** Velocidade de movimento, de \`1\` a \`7\`. */
    readonly speed: number;
    /**
     * Distância do personagem até o ponto \`(x, y)\`, em tiles.
     *
     * @param x Coordenada X do ponto, em tiles.
     * @param y Coordenada Y do ponto, em tiles.
     * @example \`\`\`js
     * if (ctx.player.distanceToPos(2100, 2105) <= 5) {
     *   ctx.macro.goToMarker('NEAR_FOUNTAIN');
     * }
     * \`\`\`
     */
    distanceToPos(x: number, y: number): number;
    /** Montaria equipada. */
    readonly mount: {
      /** Se há montaria equipada. */
      readonly equipped: boolean;
      /** ID da montaria equipada. */
      readonly itemId: number;
      /** HP atual da montaria. */
      readonly hp: number;
      /** HP máximo da montaria. */
      readonly maxHp: number;
      /** Nível da montaria. */
      readonly level: number;
      /** Vitalidade da montaria. */
      readonly vitality: number;
      /** Ração restante da montaria. */
      readonly feed: number;
      /** Nível de qualidade da montaria. */
      readonly qualityLevel: number;
    };
    /** Equipamentos do personagem, separados por slot. */
    readonly equipment: {
      /** Capacete. */
      readonly helmet: Item | null;
      /** Peitoral. */
      readonly armor: Item | null;
      /** Calça. */
      readonly pants: Item | null;
      /** Luvas. */
      readonly gloves: Item | null;
      /** Botas. */
      readonly boots: Item | null;
      /** Arma. */
      readonly weapon: Item | null;
      /** Mão secundária. */
      readonly offhand: Item | null;
      /** Brinco. */
      readonly earring: Item | null;
      /** Especial 2. */
      readonly special2: Item | null;
      /** Especial 1. */
      readonly special1: Item | null;
      /** Especial 3. */
      readonly special3: Item | null;
      /** Traje. */
      readonly costume: Item | null;
      /** Fada. */
      readonly fairy: Item | null;
      /** Montaria. */
      readonly mount: Item | null;
      /** Capa. */
      readonly cape: Item | null;
      /** Colar. */
      readonly necklace: Item | null;
      /** Cinto. */
      readonly belt: Item | null;
    };
    /**
     * A mochila do personagem, em **4 bolsas de 15 espaços** cada (60 no
     * total).
     *
     * \`\`\`js
     * if (!ctx.player.inventory.has(709)) ctx.macro.pause('sem poções');
     *
     * const total = ctx.player.inventory.count(709); // soma a quantidade em todas as bolsas
     * if (total < 50) ctx.macro.goToMarker('REFILL');
     *
     * const primeira = ctx.player.inventory.find(709);
     * if (primeira) ctx.log(\`primeira poção: bolsa \${primeira.bag! + 1}, espaço \${primeira.slot + 1}\`);
     *
     * const bolsa1 = ctx.player.inventory.bags[0].slots;
     * const ocupados = bolsa1.filter((espaco) => espaco !== null).length;
     * ctx.log(\`Bolsa 1: \${ocupados}/15 ocupados\`);
     *
     * if (ctx.player.inventory.isFull) ctx.macro.goToMarker('VENDER');
     * \`\`\`
     */
    readonly inventory: {
      /** As 4 bolsas do inventário, em ordem: \`bags[0]\` é a Bolsa 1, \`bags[3]\` é a Bolsa 4. */
      readonly bags: ReadonlyArray<{
        /** Número da bolsa (\`0..3\`, exibida como "Bolsa 1..4"). */
        readonly index: number;
        /** \`true\` quando a bolsa está bloqueada (ainda não liberada). Bolsas bloqueadas são ignoradas por \`count\`, \`find\`, \`has\`, \`freeSlots\` e \`isFull\`. */
        readonly locked: boolean;
        /** Os 15 espaços da bolsa; \`null\` é um espaço vazio. */
        readonly slots: ReadonlyArray<Item | null>;
      }>;
      /**
       * Quantidade total do item, somando as bolsas desbloqueadas (pilhas
       * contam pelo tamanho).
       *
       * @param itemId O número (id) do item que você quer contar.
       */
      count(itemId: number): number;
      /**
       * O primeiro \`Item\` com o id indicado, na ordem das bolsas.
       *
       * @param itemId O número (id) do item que você procura.
       */
      find(itemId: number): Item | null;
      /**
       * Se você tem o item.
       *
       * @param itemId O número (id) do item a verificar.
       */
      has(itemId: number): boolean;
      /** Espaços vazios nas bolsas desbloqueadas. */
      readonly freeSlots: number;
      /** Se a mochila está cheia. */
      readonly isFull: boolean;
    };
  };
  /** NPCs visíveis na sua tela. */
  readonly npcs: ReadonlyArray<Entidade>;
  /** Monstros perto do seu personagem (cerca de 6 tiles). */
  readonly monsters: ReadonlyArray<Entidade>;
  /** Outros jogadores perto do seu personagem (cerca de 6 tiles). */
  readonly otherPlayers: ReadonlyArray<Entidade>;
  /** Controles do próprio macro. O efeito só vale **depois** que o script termina de rodar, não na hora da chamada. */
  readonly macro: {
    /**
     * Pausa o macro assim que o script terminar. O motivo aparece na barra de
     * status. Se você chamar mais de uma vez, vale a última.
     *
     * @param reason Texto curto para mostrar na tela (ex.: \`"hp baixo"\`).
     * @example \`\`\`js
     * if (ctx.player.hp < 100) ctx.macro.pause('hp baixo');
     * \`\`\`
     */
    pause(reason?: string): void;
    /**
     * Salta a execução para o marcador com o nome informado, assim que o
     * script terminar.
     *
     * @param name Nome exato do marcador (diferencia maiúsculas de minúsculas).
     * @example \`\`\`js
     * if (ctx.player.hp < 100) ctx.macro.goToMarker('SAFE_AREA');
     * \`\`\`
     */
    goToMarker(name: string): void;
    /** Controle do ataque automático do macro. */
    readonly attack: {
      /**
       * Pausa o ataque automático na hora.
       *
       * @example \`\`\`js
       * if (ctx.player.hp < 50) ctx.macro.attack.pause();
       * \`\`\`
       */
      pause(): void;
      /**
       * Liga de volta o ataque automático que foi pausado por \`pause()\`.
       * Não faz nada se o ataque estiver desligado na config.
       *
       * @example \`\`\`js
       * if (ctx.player.hp > 500) ctx.macro.attack.start();
       * \`\`\`
       */
      start(): void;
      /**
       * Situação do ataque automático agora: \`'running'\` (atacando),
       * \`'paused'\` (pausado por script ou pelo macro) ou \`'disabled'\`
       * (desligado na config).
       *
       * @example \`\`\`js
       * if (ctx.macro.attack.status() === 'running') ctx.log('caçando');
       * \`\`\`
       */
      status(): "running" | "paused" | "disabled";
    };
  };
  /**
   * Memória compartilhada entre os scripts do macro: um script guarda um
   * valor aqui e outro script (ou o mesmo, numa volta seguinte) lê depois.
   * Os valores ficam guardados até o app fechar ou você limpar — sobrevivem
   * a pausa, à morte e à reconexão.
   *
   * @example \`\`\`js
   * const voltas = (ctx.memory.get('voltas') ?? 0) + 1;
   * ctx.memory.set('voltas', voltas);
   * ctx.log(\`Volta \${voltas} concluída\`);
   * \`\`\`
   */
  readonly memory: {
    /**
     * Lê o valor guardado na variável. Devolve \`undefined\` se ela nunca foi gravada.
     *
     * @param chave Nome da variável (texto).
     */
    get(chave: string): unknown;
    /**
     * Guarda um valor na variável, sobrescrevendo o valor anterior. Aceita
     * números, textos, verdadeiro/falso, listas e objetos simples.
     *
     * @param chave Nome da variável (texto).
     * @param valor Valor a guardar.
     * @example \`\`\`js
     * ctx.memory.set('ultimaCidade', 'Armia');
     * ctx.memory.set('chefesMortos', 0);
     * \`\`\`
     */
    set(chave: string, valor: unknown): void;
    /**
     * Apaga o valor guardado na variável.
     *
     * @param chave Nome da variável (texto).
     */
    delete(chave: string): void;
  };
  /**
   * Escreve uma linha no painel de logs do macro, com o prefixo \`[script]\`.
   *
   * @param message Texto a registrar (uma linha só).
   */
  log(message: string): void;
  /**
   * Mostra um aviso na tela e **pausa o macro** até você clicar em **Entendi**.
   * **Sempre use com \`await\`** — o script só continua depois do seu clique.
   *
   * @param message Texto a mostrar no aviso.
   * @example \`\`\`js
   * await ctx.alert('Chefe à vista! Confira o setup antes de seguir.');
   * ctx.macro.pause('revisar inventário');
   * \`\`\`
   */
  alert(message: string): Promise<void>;
}
declare const ctx: ScriptCtx;
`;
