/* @generated by tools/vite-plugins/script-ctx-codegen.ts — DO NOT EDIT.
 * Source of truth: src/renderer/lib/script-ctx.ts (ScriptCtx interface).
 * Regenerate: npm run dev / npm run build (the Vite plugin runs automatically).
 */
 
// prettier-ignore
export const SCRIPT_API_DOCS_MD = `
# wydbot.com — API de scripts de macro

Guia + referência completa da API de scripts de macro, em um arquivo só. Escreva steps \`script\` com acesso ao objeto global \`ctx\`.

---

# Primeiros passos

Este guia te leva do zero ao seu primeiro script de macro funcional. Se você já editou um macro antes mas nunca tinha usado um step do tipo \`script\`, comece por aqui.

## O que é um step \`script\`?

O macro do wydbot.com executa uma sequência de **steps** (\`walk\`, \`interact\`, \`delay\`, \`script\`). Quando o engine chega num step \`script\`, ele executa o código JavaScript que você escreveu, com acesso ao objeto global \`ctx\`.

Diferente dos outros steps (que descrevem _ações_), o step \`script\` descreve _decisão_: avalia o estado atual e pode pedir pra pausar o macro, logar algo, ou disparar uma ação.

## Seu primeiro script

Cole isto no editor:

\`\`\`js
ctx.log('script rodando');

if (ctx.player.hp < ctx.player.maxHp / 2) {
  ctx.macro.pause('hp baixo');
}
\`\`\`

O que acontece:

- A primeira linha imprime no painel de logs do macro.
- Se o HP estiver abaixo da metade, o macro pausa **depois** que o script termina (\`ctx.macro.pause\` é **lazy\\***, não interrompe na hora).

---

\\* **lazy** = adiado. A engine não aplica o efeito no instante da chamada — armazena a intenção e só aplica quando o script termina. Se vários \`if\` chamarem \`pause()\`, a última chamada vence.

---

# Referência da API

O objeto \`ctx\` que seu macro usa para ler o jogo e tomar decisões.

Leituras de \`player\`, \`npcs\`, \`monsters\` e \`otherPlayers\` são sempre
atualizadas: cada acesso traz o estado do jogo naquele instante.

## ctx.player

Estado do seu personagem.

- \`hp: number\` — HP atual.
- \`maxHp: number\` — HP máximo.
- \`mp: number\` — MP atual.
- \`maxMp: number\` — MP máximo.
- \`position: { x: number, y: number }\` — Posição do personagem no mapa atual, em tiles (\`x\`, \`y\`).
- \`speed: number\` — Velocidade de movimento, de \`1\` a \`7\`.
- \`distanceToPos(x: number, y: number): number\` — Distância do personagem até o ponto \`(x, y)\`, em tiles.
  - \`x\` — Coordenada X do ponto, em tiles.
  - \`y\` — Coordenada Y do ponto, em tiles.
- \`mount: { equipped: boolean, itemId: number, hp: number, maxHp: number, level: number, vitality: number, feed: number, qualityLevel: number }\` — Montaria equipada.
- \`equipment: { helmet: Item | null, armor: Item | null, pants: Item | null, gloves: Item | null, boots: Item | null, weapon: Item | null, offhand: Item | null, earring: Item | null, special2: Item | null, special1: Item | null, special3: Item | null, costume: Item | null, fairy: Item | null, mount: Item | null, cape: Item | null, necklace: Item | null, belt: Item | null }\` — Equipamentos do personagem, separados por slot.
- \`inventory: { bags: ReadonlyArray<{ index: number, locked: boolean, slots: ReadonlyArray<Item | null> }>, count(itemId: number): number, find(itemId: number): Item | null, has(itemId: number): boolean, freeSlots: number, isFull: boolean }\` — A mochila do personagem, em **4 bolsas de 15 espaços** cada (60 no total).

\`\`\`js
if (!ctx.player.inventory.has(709)) ctx.macro.pause('sem poções');

const total = ctx.player.inventory.count(709); // soma a quantidade em todas as bolsas
if (total < 50) ctx.macro.goToMarker('REFILL');

const primeira = ctx.player.inventory.find(709);
if (primeira) ctx.log(\`primeira poção: bolsa \${primeira.bag! + 1}, espaço \${primeira.slot + 1}\`);

const bolsa1 = ctx.player.inventory.bags[0].slots;
const ocupados = bolsa1.filter((espaco) => espaco !== null).length;
ctx.log(\`Bolsa 1: \${ocupados}/15 ocupados\`);

if (ctx.player.inventory.isFull) ctx.macro.goToMarker('VENDER');
\`\`\`

Exemplo de \`distanceToPos\`:

\`\`\`js
if (ctx.player.distanceToPos(2100, 2105) <= 5) {
  ctx.macro.goToMarker('NEAR_FOUNTAIN');
}
\`\`\`

## ctx.npcs

NPCs visíveis na sua tela.

- \`npcs: ReadonlyArray<Entidade>\`
- Cada item é um \`Entidade\` — veja a seção **Entidade** abaixo.

## ctx.monsters

Monstros perto do seu personagem (cerca de 6 tiles).

- \`monsters: ReadonlyArray<Entidade>\`
- Cada item é um \`Entidade\` — veja a seção **Entidade** abaixo.

## ctx.otherPlayers

Outros jogadores perto do seu personagem (cerca de 6 tiles).

- \`otherPlayers: ReadonlyArray<Entidade>\`
- Cada item é um \`Entidade\` — veja a seção **Entidade** abaixo.

## ctx.macro

Controles do próprio macro. O efeito só vale **depois** que o script termina de rodar, não na hora da chamada.

- \`pause(reason?: string): void\` — Pausa o macro assim que o script terminar. O motivo aparece na barra de status. Se você chamar mais de uma vez, vale a última.
  - \`reason\` — Texto curto para mostrar na tela (ex.: \`"hp baixo"\`).
- \`goToMarker(name: string): void\` — Salta a execução para o marcador com o nome informado, assim que o script terminar.
  - \`name\` — Nome exato do marcador (diferencia maiúsculas de minúsculas).
- \`attack: { pause(): void, start(): void, status(): "running" | "paused" | "disabled" }\` — Controle do ataque automático do macro.

Exemplo de \`pause\`:

\`\`\`js
if (ctx.player.hp < 100) ctx.macro.pause('hp baixo');
\`\`\`

Exemplo de \`goToMarker\`:

\`\`\`js
if (ctx.player.hp < 100) ctx.macro.goToMarker('SAFE_AREA');
\`\`\`

## ctx.memory

Memória compartilhada entre os scripts do macro: um script guarda um
valor aqui e outro script (ou o mesmo, numa volta seguinte) lê depois.
Os valores ficam guardados até o app fechar ou você limpar — sobrevivem
a pausa, à morte e à reconexão.

- \`get(chave: string): unknown\` — Lê o valor guardado na variável. Devolve \`undefined\` se ela nunca foi gravada.
  - \`chave\` — Nome da variável (texto).
- \`set(chave: string, valor: unknown): void\` — Guarda um valor na variável, sobrescrevendo o valor anterior. Aceita números, textos, verdadeiro/falso, listas e objetos simples.
  - \`chave\` — Nome da variável (texto).
  - \`valor\` — Valor a guardar.
- \`delete(chave: string): void\` — Apaga o valor guardado na variável.
  - \`chave\` — Nome da variável (texto).

Exemplo de \`set\`:

\`\`\`js
ctx.memory.set('ultimaCidade', 'Armia');
ctx.memory.set('chefesMortos', 0);
\`\`\`

## ctx.log()

Escreve uma linha no painel de logs do macro, com o prefixo \`[script]\`.

- \`log(message: string): void\`
  - \`message\` — Texto a registrar (uma linha só).

## ctx.alert()

Mostra um aviso na tela e **pausa o macro** até você clicar em **Entendi**.
**Sempre use com \`await\`** — o script só continua depois do seu clique.

- \`alert(message: string): Promise<void>\`
  - \`message\` — Texto a mostrar no aviso.

Exemplo de \`alert\`:

\`\`\`js
await ctx.alert('Chefe à vista! Confira o setup antes de seguir.');
ctx.macro.pause('revisar inventário');
\`\`\`

## Item

Um item do personagem (equipamento ou do inventário).

- \`slot: number\` — Posição do item no equipamento ou na bolsa (\`0..14\`).
- \`bag?: number\` — Bolsa do item (\`0..3\`). Só em itens do inventário.
- \`itemId: number\` — ID do item.
- \`name: string\` — Nome do item, já com sufixos como \`+N\` e \`[G]\`.
- \`refineLevel?: number\` — Nível de refino (\`+1..+16\`).
- \`stackCount?: number\` — Quantidade na pilha (\`1..500\`).
- \`immovable?: 1 | 2 | 3\` — Item preso (valores na tabela abaixo da página).
- \`useKind: "direto" | "pergaminho" | "popup" | "painel" | "equipamento" | "bloqueado"\` — Como o jogo reage ao usar o item (valores na tabela abaixo da página).
- \`use?(): void\` — Usa o item (consome), disparado depois que o script termina. Só existe em consumíveis de uso direto (\`useKind === 'direto'\`).
- \`delete?(): void\` — Apaga o item da bolsa (joga fora). **O efeito só acontece depois que o script termina**, não na hora da chamada — igual a \`use()\`. Enquanto o script ainda roda, o item continua visível no inventário. Só existe em itens do inventário (bolsas), nunca em equipamentos. Alguns itens não podem ser apagados pelo jogo; nesse caso o item volta para a bolsa sozinho. Se o script chamar \`delete()\` mais de uma vez, vale a **última** chamada (só um item é apagado por execução).
- \`stats: ReadonlyArray<{ id: string, label: string, value: number }>\` — Os atributos do item, como no tooltip. Cada um traz \`id\`, \`label\` e \`value\`.
- \`scroll?: { destinations: ReadonlyArray<{ name: string, x: number, y: number }>, use(destino?: { x: number, y: number }): void }\` — Só existe em pergaminhos (\`useKind === 'pergaminho'\`). Na caça, \`destinations\` lista os lugares; em retorno/teleporte/portal, vem vazia.

## ItemShort

Uma peça visível de uma entidade: só id e nome.

- \`itemId: number\` — Número (id) do item.
- \`name: string\` — Nome do item. Pode vir vazio no modelo do corpo de um monstro.

## Entidade

Um NPC, monstro ou outro jogador no mapa.

- \`index: number\` — Identificador da entidade. Vale só enquanto você está conectado: muda a cada novo login.
- \`name: string\` — Nome da entidade.
- \`position: { x: number, y: number }\` — Posição da entidade no mapa atual, em tiles (\`x\`, \`y\`).
- \`appearance: { body: ItemShort | null, helmet: ItemShort | null, armor: ItemShort | null, pants: ItemShort | null, gloves: ItemShort | null, boots: ItemShort | null, weapon: ItemShort | null, offhand: ItemShort | null, earring: ItemShort | null, special2: ItemShort | null, special1: ItemShort | null, special3: ItemShort | null, costume: ItemShort | null, fairy: ItemShort | null, mount: ItemShort | null, cape: ItemShort | null }\` — O visual da entidade: o modelo do corpo e as peças que ela usa. Os slots são os mesmos de \`ctx.player.equipment\`.
- \`isWithin(tiles: number): boolean\` — Se a entidade está a até \`tiles\` passos do personagem.
  - \`tiles\` — Distância máxima, em tiles (passos).
`;
