/**
 * Renderers that turn ScriptCtxMeta back into the on-disk artefacts:
 *
 * - `renderDts(meta)` — the `.generated.ts` source containing
 *   `export const SCRIPT_CTX_DTS = \`...\`;`. The body is canonical TS source
 *   reconstructed from the meta, including JSDoc blocks. Backticks, dollar
 *   signs and backslashes are escaped for the template literal wrapper.
 * - `renderJson(meta)` — `JSON.stringify(meta, null, 2)` + trailing newline.
 * - `renderAiMarkdown(meta, guideMarkdown)` — single-file markdown (guide +
 *   full API reference) exported as `SCRIPT_API_DOCS_MD` from
 *   `script-api-docs.generated.ts`. Consumed by the "Copiar markdown da API"
 *   action in the script editor — the user pastes it into an assistant.
 *
 * Exhaustiveness on `TypeMeta` variants is enforced via a `never`-typed
 * default branch — adding a new variant breaks compilation here.
 */
import type {
  InterfaceMeta,
  JsDocMeta,
  MemberMeta,
  MethodMemberMeta,
  ParamMeta,
  ScriptCtxMeta,
  TypeMeta,
} from './script-ctx-codegen-types';

const BANNER = `/* @generated by tools/vite-plugins/script-ctx-codegen.ts — DO NOT EDIT.
 * Source of truth: src/renderer/lib/script-ctx.ts (ScriptCtx interface).
 * Regenerate: npm run dev / npm run build (the Vite plugin runs automatically).
 */
/* eslint-disable */
// prettier-ignore
`;

export const renderDts = (meta: ScriptCtxMeta): string => {
  const declarations = meta.interfaces.map(renderInterfaceAsDeclare).join('\n');
  const body = `${declarations}\ndeclare const ctx: ScriptCtx;\n`;
  return `${BANNER}export const SCRIPT_CTX_DTS = \`\n${escapeForTemplateLiteral(body)}\`;\n`;
};

export const renderJson = (meta: ScriptCtxMeta): string => `${JSON.stringify(meta, null, 2)}\n`;

/**
 * Single-file markdown (guide + API reference) exported as
 * `SCRIPT_API_DOCS_MD`. The guide must stay free of VitePress-only
 * directives (`::: details`, `{{ }}`) — they would leak verbatim.
 */
export const renderAiMarkdown = (meta: ScriptCtxMeta, guideMarkdown: string): string => {
  const ctx = meta.interfaces.find((i) => i.name === 'ScriptCtx');
  const auxInterfaces = meta.interfaces.filter((i) => i.name !== 'ScriptCtx');

  const parts: string[] = [
    '# wydbot.com — API de scripts de macro',
    '',
    'Guia + referência completa da API de scripts de macro, em um arquivo só. Escreva steps `script` com acesso ao objeto global `ctx`.',
    '',
    '---',
    '',
    stripFrontmatter(guideMarkdown).trim(),
    '',
    '---',
    '',
    '# Referência da API',
  ];

  if (ctx) {
    if (ctx.jsDoc?.description) {
      parts.push('', ctx.jsDoc.description);
    }
    const auxNames = auxInterfaces.map((i) => i.name);
    for (const member of ctx.members) {
      parts.push('', renderCtxMemberSection(member, auxNames));
    }
  }

  for (const iface of auxInterfaces) {
    parts.push('', renderInterfaceSection(iface));
  }

  const body = `${parts.join('\n')}\n`;
  return `${BANNER}export const SCRIPT_API_DOCS_MD = \`\n${escapeForTemplateLiteral(body)}\`;\n`;
};

const renderCtxMemberSection = (member: MemberMeta, auxNames: readonly string[]): string => {
  const title = member.kind === 'method' ? `ctx.${member.name}()` : `ctx.${member.name}`;
  const lines: string[] = [`## ${title}`, ''];
  if (member.jsDoc?.description) {
    lines.push(member.jsDoc.description, '');
  }

  if (member.kind === 'property' && member.type.kind === 'object') {
    for (const sub of member.type.members) {
      lines.push(...renderMemberBullet(sub));
    }
  } else if (member.kind === 'method') {
    // Signature first so the return type stays visible (e.g. `alert(): Promise<void>`).
    lines.push(`- \`${renderInlineSignature(member)}\``);
    for (const param of member.params) {
      const desc = paramDesc(member, param);
      lines.push(`  - \`${param.name}\`${desc ? ` — ${desc}` : ''}`);
    }
    if (member.jsDoc?.returns) {
      lines.push(`  - Retorna ${member.jsDoc.returns}`);
    }
  } else {
    // Array/scalar member — point to the aux interface section when the
    // element type is a documented interface (e.g. `npcs` → `Entidade`).
    lines.push(`- \`${member.name}: ${renderInlineType(member.type)}\``);
    const ref = collectInterfaceRef(member.type, auxNames);
    if (ref) {
      lines.push(`- Cada item é um \`${ref}\` — veja a seção **${ref}** abaixo.`);
    }
  }

  lines.push(...renderMemberExamples(member));
  return lines.join('\n').trimEnd();
};

const collectInterfaceRef = (type: TypeMeta, auxNames: readonly string[]): string | null => {
  if (type.kind === 'reference' && auxNames.includes(type.name)) return type.name;
  if (type.kind === 'array') return collectInterfaceRef(type.element, auxNames);
  return null;
};

const renderInterfaceSection = (iface: InterfaceMeta): string => {
  const lines: string[] = [`## ${iface.name}`, ''];
  if (iface.jsDoc?.description) {
    lines.push(iface.jsDoc.description, '');
  }
  for (const member of iface.members) {
    lines.push(...renderMemberBullet(member));
  }
  return lines.join('\n').trimEnd();
};

const renderMemberBullet = (member: MemberMeta): string[] => {
  const opt = member.optional ? '?' : '';
  // Descriptions may span lines or embed a fenced example: prose goes inline
  // in the bullet, the fence moves to its own block below.
  const { inline, block } = splitDesc(member.jsDoc?.description);
  const lines: string[] = [];

  if (member.kind === 'property') {
    lines.push(
      `- \`${member.name}${opt}: ${renderInlineType(member.type)}\`${inline ? ` — ${inline}` : ''}`,
    );
  } else {
    lines.push(`- \`${renderInlineSignature(member)}\`${inline ? ` — ${inline}` : ''}`);
    for (const param of member.params) {
      const desc = paramDesc(member, param);
      if (desc) {
        lines.push(`  - \`${param.name}\` — ${desc}`);
      }
    }
    if (member.jsDoc?.returns) {
      lines.push(`  - Retorna ${member.jsDoc.returns}`);
    }
  }

  if (block) {
    lines.push('', block);
  }
  return lines;
};

/** Splits off a fenced code block embedded in a JSDoc description. */
const splitDesc = (desc: string | null | undefined): { inline: string; block: string } => {
  const fenceIndex = desc?.indexOf('```') ?? -1;
  if (!desc || fenceIndex === -1) {
    return { inline: inlineDesc(desc), block: '' };
  }
  return { inline: inlineDesc(desc.slice(0, fenceIndex)), block: desc.slice(fenceIndex).trim() };
};

const paramDesc = (member: MethodMemberMeta, param: ParamMeta): string =>
  inlineDesc(param.description ?? member.jsDoc?.params[param.name]);

const renderInlineSignature = (member: MethodMemberMeta): string =>
  renderMemberSignature(member, '').replace(/;$/, '');

const inlineDesc = (desc: string | null | undefined): string =>
  (desc ?? '').replace(/\s*\n\s*/g, ' ').trim();

const stripFrontmatter = (markdown: string): string =>
  markdown.replace(/^---\n[\s\S]*?\n---\n?/, '');

const renderMemberExamples = (member: MemberMeta): string[] => {
  const sources: readonly MemberMeta[] =
    member.kind === 'property' && member.type.kind === 'object' ? member.type.members : [member];
  const blocks: string[] = [];
  for (const source of sources) {
    const examples = source.jsDoc?.tags.filter((t) => t.tag === 'example' && t.text) ?? [];
    for (const example of examples) {
      blocks.push('', `Exemplo de \`${source.name}\`:`, '', example.text.trim());
    }
  }
  return blocks;
};

/** Single-line type rendering (object types collapse inline). */
const renderInlineType = (type: TypeMeta): string => {
  switch (type.kind) {
    case 'object': {
      if (type.members.length === 0) return '{}';
      const fields = type.members
        .map((m) =>
          m.kind === 'property'
            ? `${m.name}${m.optional ? '?' : ''}: ${renderInlineType(m.type)}`
            : `${m.name}${m.optional ? '?' : ''}(${m.params
                .map((p) => `${p.name}${p.optional ? '?' : ''}: ${renderInlineType(p.type)}`)
                .join(', ')}): ${renderInlineType(m.returns)}`,
        )
        .join(', ');
      return `{ ${fields} }`;
    }
    case 'array': {
      const inner = renderInlineType(type.element);
      return type.readonly ? `ReadonlyArray<${inner}>` : `${inner}[]`;
    }
    case 'reference': {
      if (type.typeArgs.length === 0) return type.name;
      return `${type.name}<${type.typeArgs.map(renderInlineType).join(', ')}>`;
    }
    case 'promise':
      return `Promise<${renderInlineType(type.resolved)}>`;
    case 'union':
      return type.variants.map(renderInlineType).join(' | ');
    default:
      return renderType(type, '');
  }
};

const renderInterfaceAsDeclare = (iface: InterfaceMeta): string => {
  const docBlock = renderJsDocBlock(iface.jsDoc, '');
  const memberLines = iface.members.map((m) => renderMember(m, '  ')).join('\n');
  return `${docBlock}declare interface ${iface.name} {\n${memberLines}\n}`;
};

const renderMember = (member: MemberMeta, indent: string): string => {
  const docBlock = renderJsDocBlock(member.jsDoc, indent);
  return `${docBlock}${indent}${renderMemberSignature(member, indent)}`;
};

const renderMemberSignature = (member: MemberMeta, indent: string): string => {
  if (member.kind === 'property') {
    const ro = member.readonly ? 'readonly ' : '';
    const opt = member.optional ? '?' : '';
    return `${ro}${member.name}${opt}: ${renderType(member.type, indent)};`;
  }
  const opt = member.optional ? '?' : '';
  const params = member.params.map((p) => renderParam(p, indent)).join(', ');
  return `${member.name}${opt}(${params}): ${renderType(member.returns, indent)};`;
};

// `indent` is the member's column so an inline-object-literal param (e.g. `use(d?: { x; y })`)
// aligns its braces under the method instead of collapsing to column 0.
const renderParam = (param: ParamMeta, indent: string): string => {
  const opt = param.optional ? '?' : '';
  return `${param.name}${opt}: ${renderType(param.type, indent)}`;
};

const renderType = (type: TypeMeta, indent: string): string => {
  switch (type.kind) {
    case 'primitive':
      return type.name;
    case 'literal':
      return typeof type.value === 'string' ? JSON.stringify(type.value) : String(type.value);
    case 'reference': {
      if (type.typeArgs.length === 0) return type.name;
      const args = type.typeArgs.map((a) => renderType(a, indent)).join(', ');
      return `${type.name}<${args}>`;
    }
    case 'array': {
      const inner = renderType(type.element, indent);
      return type.readonly ? `ReadonlyArray<${inner}>` : `${inner}[]`;
    }
    case 'object':
      return renderObjectType(type.members, indent);
    case 'promise':
      return `Promise<${renderType(type.resolved, indent)}>`;
    case 'union':
      return type.variants.map((v) => renderType(v, indent)).join(' | ');
    case 'unsupported':
      return type.raw;
    default: {
      const _exhaustive: never = type;
      return _exhaustive;
    }
  }
};

const renderObjectType = (members: readonly MemberMeta[], indent: string): string => {
  if (members.length === 0) return '{}';
  const innerIndent = `${indent}  `;
  const lines = members.map((m) => renderMember(m, innerIndent)).join('\n');
  return `{\n${lines}\n${indent}}`;
};

const renderJsDocBlock = (jsDoc: JsDocMeta | null, indent: string): string => {
  if (!jsDoc) return '';

  const lines: string[] = [];
  if (jsDoc.description) {
    lines.push(...jsDoc.description.split('\n'));
  }

  const tagLines: string[] = [];
  const pushTag = (head: string, text: string): void => {
    if (!text) {
      tagLines.push(head);
      return;
    }
    const [first, ...rest] = text.split('\n');
    tagLines.push(`${head} ${first}`);
    for (const line of rest) tagLines.push(line);
  };
  for (const [name, desc] of Object.entries(jsDoc.params)) {
    pushTag(`@param ${name}`, desc);
  }
  if (jsDoc.returns) {
    pushTag('@returns', jsDoc.returns);
  }
  for (const { tag, text } of jsDoc.tags) {
    pushTag(`@${tag}`, text);
  }

  if (lines.length > 0 && tagLines.length > 0) {
    lines.push('');
  }
  lines.push(...tagLines);

  if (lines.length === 0) return '';
  if (lines.length === 1 && !lines[0]?.includes('\n')) {
    return `${indent}/** ${lines[0]} */\n`;
  }

  const body = lines.map((line) => (line ? `${indent} * ${line}` : `${indent} *`)).join('\n');
  return `${indent}/**\n${body}\n${indent} */\n`;
};

const escapeForTemplateLiteral = (s: string): string =>
  s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

/**
 * Replaces the `generatedAt` ISO timestamp in a rendered JSON string with an
 * empty string. Used by the CLI `--check` mode and by the plugin's diff
 * cache to compare two renders for *structural* equality (ignoring the
 * timestamp that changes on every run).
 */
export const stripGeneratedAt = (jsonText: string): string =>
  jsonText.replace(/"generatedAt": "[^"]*"/, '"generatedAt": ""');
